### ISSUE TITLE
Gutschrift berechnet Umsatzsteuer nicht korrekt

### ISSUE THREAD

**Issue by andreasmuellerka** [tomka/rechnung#14]
Wird eine Gutschrift angegeben:
\Gutschrift{Guthaben aus XY}{100,00}, dann wird für die Umsatzsteuer -18,99 EUR ausgerechnet anstatt -19,00 EUR.

**Comment by tomka** [comment]
Danke für den Bug-Report! Ich versuch mir das demnächst mal anzuschauen.

**Comment by tomka** [comment]
Mit 463652c sollte ich das endlich gefixt haben. Danke für den Beispielcode.
