### ISSUE TITLE
Tausenderpunk

### ISSUE THREAD

**Issue by leofuehringer** [tomka/rechnung#16]
Hallo,
ist es möglich alle Werte mit einem 1000er-Punkt zu versehen, damit man die Rechnungsbeträge besser lesen kann?
Danke und liebe Grüße

**Comment by tomka** [comment]
Danke, das ist ein guter Vorschlag. Tausendertrennzeichen auf Basis von `siunitx` sind nun standardmäßig aktiviert und können mit `\TausenderTrennzeichenEin`/-`Aus` kontrolliert werden. Mit Hilfe von `\TausenderTrennzeichen` kann das entsprechende Trennzeichen gesetzt werden (ein Punkt ist da der Default-Wert).

**Comment by leofuehringer** [comment]
Toll! Vielen Dank! Freut mich sehr...
