### ISSUE TITLE
Gutschrift führt du merkwürdiger Gesamtsumme

### ISSUE THREAD

**Issue by andreasmuellerka** [tomka/rechnung#8]
Wird eine Gutschrift angegeben:
`\Gutschrift{Guthaben aus XY}{99,99}`, dann wird in der Spalte Gesamtpreis nicht etwa
`-99,99 €` angezeigt, sondern
`-99,-9-9 €`

Es werden also insgesamt drei Minuszeichen erzeugt.
Leider kenne ich mich in Latex zu wenig aus, um den Bug selbst zu beheben.

**Comment by tomka** [comment]
Danke für den Bugreport! Ich kann nicht versprechen wann ich dazu komme, aber ich werde versuchen mir das bald anzusehen.

**Comment by tomka** [comment]
Jetzt bin ich endlich mal dazu gekommen mir das anzusehen und hab einen Fix für das Anzeigeproblem negativer Zahlen gefunden. Die Rechnung selbst war nicht falsch, lediglich die Ausgabe der Zahlen (da explizit auf zwei Stellen abgeschnitten wird).
